pip install librosa
pip install soundfile
pip install scipy
pip install datetime
pip install pytz
pip install logging
pip install pandas
pip install scikit-learn
pip install praat-parselmouth
pip install numpy==1.26.4